### ISSUE TITLE
Operate on COM port

### ISSUE THREAD

**Issue by JucaTec** [dioannidis/libUSBUARTTerminal#1]
Hi.

I would like to thank you for the work and ask if it is possible to make the program work with COM port or USB-Serial adapters with FTDI and Prolific?

I know you have several programs for this, but it would be very convenient to have everything in one program.

Thank you.

**Comment by dioannidis** [comment]
Hi,
  
  AFAIU, you propose to make the project a generic UART client ? 

  I really don't see the point for doing this. Could you please elaborate ?

regards,

**Comment by JucaTec** [comment]
Hi. 

It would be to have in just one program the option to use with USBasp and generic serial.

**Comment by JucaTec** [comment]
I'm trying to port the firmware to Atemega88 too.

**Comment by dioannidis** [comment]
@JucaTec 

FYI, I'll have a version of usbasp for atmega8 and atmega88pa soon. It will have a HID serial ( not CDC ) implementation running max at 4800 baud, in a week or two. Currently I'm trying to push it to 9600 baud but with no success yet.

The code is at https://github.com/dioannidis/usbasp .

**Comment by JucaTec** [comment]
@dioannidis

Thank you.
