### ISSUE TITLE
access violation

### ISSUE THREAD

**Issue by MaxBayne** [dioannidis/libUSBUARTTerminal#3]
i have this error

![usbasp](https://user-images.githubusercontent.com/8224490/205560402-cf9c5c7b-5ec5-44cd-8cf7-a629cdc5744b.png)

my setup as it below

- burn the firmware (firmware\main.hex) to my usbasp
- remove jumper of self programming
- use MCU ATMEGA32A
- make my MCU Initialize UART as Baud Rate 9600 and make it send Text every 1 second to UART just for testing Purpose
- connect MCU to USBASP
- connect the RX of USBASP > TX of MCU
- connect the TX of USBASP > RX of MCU
- open (USBasp UART Terminal) and Connect successfully
- when try open then display this error message and nothing received
- i expected to receive the text sent fro, mcu over UART inside Terminal but nothing happen
- i didn't make any Hardware modification of my USBasp stick , just burn firmware

any help please . thanks

**Comment by dioannidis** [comment]
Hi @MaxBayne ,

which usbasp device do you have ? 

Can you check if the USBasp mcu's Rx/Tx pins are exposed at the connector ?
( I assume that you didn't forgot to connect the gnd also between USBasp and atmega32a )

 Also, did you try with the [usbasphiduart](https://github.com/dioannidis/usbasp#usbasphiduart-utility) utility first to see if it works ?

**Comment by MaxBayne** [comment]
thanks @dioannidis  for replay

i use this usbasp

![usbasp](https://user-images.githubusercontent.com/8224490/205982846-97dc90c7-36ad-498e-a5c2-9ae02dce8a97.png)

Can you check if the USBasp mcu's Rx/Tx pins are exposed at the connector ?

yes i check it with my multi meter 
pin TX (usbasp) connected with Connector 4 throw resistor 1k
pin RX(usbasp) connected with connector 6

( I assume that you didn't forgot to connect the gnd also between USBasp and atmega32a )
i use the power and ground from usbasp to power my atmega32a

did you try with the [usbasphiduart](https://github.com/dioannidis/usbasp#usbasphiduart-utility) utility first to see if it works ?

i tried it but nothing work
![usbasohiduart_console](https://user-images.githubusercontent.com/8224490/205985887-7696ca73-1d10-44a7-80c3-fe0541413039.png)

beside i can detect my mcu using usbasp throw avrdude
![avr_dude](https://user-images.githubusercontent.com/8224490/205986033-bc4da784-b6e5-405c-99de-b065d63d110c.png)

**Comment by dioannidis** [comment]
If you used zadig as the USBasp driver, try to uninstall it. 

Connect the USBasp, go to the Device Manager, select the USBasp device and uninstall it with the "delete the driver software" option checked ( see here [Uninstalling a driver completely](https://answers.microsoft.com/en-us/windows/forum/all/uninstalling-a-driver-completely/8b7195cb-0d74-4ddf-ad55-ac0bcbf76f22) ). 

This is how it should look the USBasp in Device Manager, a composite usb device, a winusb device and a HID device all with the same vid, pid : 


![USBaspDevice](https://user-images.githubusercontent.com/15191633/206005240-159a216b-96c3-45a6-b7d6-d6a4ce9ee1a7.JPG)

**Comment by MaxBayne** [comment]
thanks again @dioannidis 
i already used zadig as the USBasp driver
this is my screenshot
what do you suggest to fix this issue ?
![usbasp](https://user-images.githubusercontent.com/8224490/206284353-128c1d3b-434b-41fe-b31e-bc30b3340af2.png)

**Comment by dioannidis** [comment]
> thanks again @dioannidis i already used zadig as the USBasp driver this is my screenshot what do you suggest to fix this issue ? 

as I posted earlier uninstall the zadig driver , see here [Uninstalling a driver completely](https://answers.microsoft.com/en-us/windows/forum/all/uninstalling-a-driver-completely/8b7195cb-0d74-4ddf-ad55-ac0bcbf76f22) or here [Help, Zadig replaced the driver for the wrong device! How do I restore it?](https://github.com/pbatard/libwdi/wiki/FAQ#help-zadig-replaced-the-driver-for-the-wrong-device-how-do-i-restore-it) on how to do the uninstallation .

I don't know how the avrdudess works but AFAIK the avrdude 7.0 doesn't work with composite devices see :

- [avrdude with composite device firmware ( usbasp with winusb and hid )](https://github.com/avrdudes/avrdude/issues/968) 
- [the Avrdude section in USBasp](https://github.com/dioannidis/usbasp#avrdude) 

You could replace the avrdude.exe 7.0 in the avrdudess installation with the unofficial, libusb enabled avrdude.exe 7.0 from [mcuee's repo](https://github.com/mcuee/avrdude/releases/tag/v7.0) . I don't use avrdudess but I can give it a try if you have still have problem .

**Comment by MaxBayne** [comment]
thanks so much
